version: "3.7"

services:
  app:
    image: pitcentr/chess-telegram-bot:1.0.9
    user: "1000:1000"
    init: true
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      TG_TOKEN: ""
      PB_URL: "http://pocketbase_app_1:8090"
      PB_ADMIN: ""
      PB_PASSWORD: ""
